### ISSUE TITLE
Проверка ДЗ4

### ISSUE THREAD

**Issue by Damovetsky** [1mavic/to-do-app#6]
Привет, я проверяю твою работу в рамках 4 дз.
Давай сразу к критериям:
* Чистота кода и общая структура проекта 5/5
* Навигация 1/1
* Обрезка по макету 1/1
* Ночная тема 1/1
* За анимации полный балл поставить не могу, потому что при добавлении новой задачи и редактировании у тебя сначала часть списка прорисовывается одним кадром, и только другим уже весь список и анимации там нет. У меня также было, я чтобы такое поведение поправить, переходил на AnimatedList, тогда всё плавно. А пока это довольно критичный баг 0/1
* Лендскейп-ориентация 2/2
* Поддержка планшетов 2/2 (за формат master-details отдельный респект, там правда есть некоторые проблемки со сбросом полей, при добавлении новой задачи, но всё равно очень круто, что ты именно так этот критерий реализовал)
* Remote configs + Crashlytics  судя по коду всё должно работать без проблем 3/3
* На счёт флейворов у меня есть к тебе вопрос. Дело в том, что когда я прогоняю те команды, которые ты в README указал, у меня что на телефоне, что на планшете приложение запускается в таком виде: 
![image](https://github.com/1mavic/to-do-app/assets/124775284/1751601b-7142-42e5-a32a-ebf464c5daf9)
![image](https://github.com/1mavic/to-do-app/assets/124775284/772edd8e-dde9-46e5-a4fd-be52efe6e2ba)
Признаюсь, я не сильно разбирался почему так происходит. Потому что тестил всё по твоим релизам и там всё вроде как работает. Но так как эти команды тоже относятся к критерию, я пока склонен поставить половину баллов, но если ты пояснишь в чем дело, я оценку повышу. Вообще не исключено, что я в чём-то туплю, но делаю я всё как в readme) 1/2
* Настроен CI на GitHub 4/4
* Но вот не увидел в твоих workflow взаимодействия с App Distribution. Если ты реализовывал этот критерий, то поясни, пожалуйста, в каком виде. Потому что, как я понял, распространение через App Distribution у тебя должно быть в твой CI интегрировано, пока 0/2
* Разное 2/2

Таким образом пока получается 22/26
В целом мне понравилась структура и уровень декомпозиции твоего кода. Хотел бы уточнить у тебя все моменты, которые под вопросом и поставить оценку повыше. Поэтому отпишись, пожалуйста, по вопросам здесь или лучше напрямую мне в тг: @Accordion_Palych. Удачи тебе в отборе на второй этап и успехов во Flutter!

**Comment by 1mavic** [comment]
@Damovetsky добрый дерь!
Спасибо за ревью.
Если показывает такой экран значит через dart-define неверный урл прокидываете.

**Comment by Damovetsky** [comment]
Да, пожалуй дело в этом. Тогда с флейворами всё хорошо, ставлю по ним 2/2
